/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eef0ff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#101e1a',
        error: '#ba1a1a',
        'on-background': '#131b2e',
        'surface-tint': '#006c49',
        'on-primary-container': '#00422b',
        'on-tertiary': '#ffffff',
        outline: '#6c7a71',
        'outline-variant': '#bbcabf',
        'surface-container-lowest': '#ffffff',
        primary: '#006c49',
        'on-tertiary-container': '#2d3c37',
        'surface-variant': '#dae2fd',
        'surface-container-highest': '#dae2fd',
        'on-secondary': '#ffffff',
        surface: '#faf8ff',
        'inverse-primary': '#4edea3',
        'secondary-container': '#64f9bc',
        'inverse-surface': '#283044',
        'surface-container-low': '#f2f3ff',
        'on-surface': '#131b2e',
        tertiary: '#52625c',
        'tertiary-fixed': '#d5e6df',
        background: '#faf8ff',
        'on-primary': '#ffffff',
        'secondary-fixed': '#68fcbf',
        'surface-container-high': '#e2e7ff',
        'primary-fixed-dim': '#4edea3',
        'on-primary-fixed-variant': '#005236',
        'primary-container': '#10b981',
        'tertiary-container': '#96a69f',
        secondary: '#006c4b',
        'surface-bright': '#faf8ff',
        'surface-dim': '#d2d9f4',
        'on-secondary-fixed-variant': '#005137',
        'primary-fixed': '#6ffbbe',
        'on-primary-fixed': '#002113',
        'secondary-fixed-dim': '#45dfa4',
        'surface-container': '#eaedff',
        'on-surface-variant': '#3c4a42',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#bacac3',
        'on-tertiary-fixed-variant': '#3b4a44',
        'on-secondary-container': '#00714e',
        'on-secondary-fixed': '#002114',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'section-gap': '64px',
        'stack-lg': '32px',
        'container-padding': '32px',
        gutter: '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
